version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - capturechronicles

  gallery:
    build:
      context: ./gallery
      dockerfile: Dockerfile.gallery
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://api:5000
    networks:
      - capturechronicles
    depends_on:
      - api

networks:
  capturechronicles:
    driver: bridge
